"""0003 layer 3 regulatory intelligence foundation

Revision ID: da97e73093ce
Revises: df4721c77cfb
Create Date: 2026-09-27 07:42:18.167587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da97e73093ce'
down_revision = 'df4721c77cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Manually added — see the 0002 migration for why (new Postgres
    # enum labels aren't autogenerated).
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'INTELLIGENCE_SOURCE'")
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'INTELLIGENCE_CONFIGURATION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_tags',
    sa.Column('tag_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_type', 'name', name='uq_intelligence_tag_type_name')
    )
    op.create_table('intelligence_sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('REGULATORY_AUTHORITY', 'INDUSTRY_PUBLICATION', 'NEWS_AGGREGATOR', 'OTHER', name='intelligence_source_type'), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('country_region', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('collection_method', sa.Enum('MANUAL', 'RSS', 'API', 'SCRAPE', name='intelligence_collection_method'), nullable=False),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('reliability_notes', sa.Text(), nullable=True),
    sa.Column('last_successful_collection_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_collection_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('configuration_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_intelligence_items',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'TENANT', 'PRIVATE', name='intelligence_scope'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_content_reference', sa.Text(), nullable=True),
    sa.Column('intelligence_type', sa.Enum('REGULATORY_GUIDELINE', 'REGULATORY_CHANGE', 'AGENCY_NEWS', 'INDUSTRY_NEWS', 'TENDER_ALERT', 'PATENT_CLIFF', 'PARA_IV_CHALLENGE', 'PHARMA_EVENT', 'SAFETY_COMPLIANCE_ALERT', name='intelligence_type'), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('country_region', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_review_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'PUBLISHED', 'WITHDRAWN', 'ARCHIVED', name='intelligence_status'), nullable=False),
    sa.Column('impact_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='impact_level'), nullable=False),
    sa.Column('impact_reason', sa.Text(), nullable=False),
    sa.Column('impact_assessed_by', sa.UUID(), nullable=True),
    sa.Column('impact_assessment_source', sa.String(length=32), nullable=False),
    sa.Column('therapeutic_area', sa.String(length=255), nullable=True),
    sa.Column('regulatory_area', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_intelligence_items_intelligence_type'), 'regulatory_intelligence_items', ['intelligence_type'], unique=False)
    op.create_index(op.f('ix_regulatory_intelligence_items_organization_id'), 'regulatory_intelligence_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regulatory_intelligence_items_scope'), 'regulatory_intelligence_items', ['scope'], unique=False)
    op.create_index(op.f('ix_regulatory_intelligence_items_status'), 'regulatory_intelligence_items', ['status'], unique=False)
    op.create_table('intelligence_distributions',
    sa.Column('intelligence_item_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distributed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['regulatory_intelligence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intelligence_item_id', 'organization_id', name='uq_intelligence_distribution')
    )
    op.create_index(op.f('ix_intelligence_distributions_intelligence_item_id'), 'intelligence_distributions', ['intelligence_item_id'], unique=False)
    op.create_index(op.f('ix_intelligence_distributions_organization_id'), 'intelligence_distributions', ['organization_id'], unique=False)
    op.create_table('intelligence_item_tags',
    sa.Column('intelligence_item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['regulatory_intelligence_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['intelligence_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intelligence_item_id', 'tag_id')
    )
    op.create_table('intelligence_object_links',
    sa.Column('intelligence_item_id', sa.UUID(), nullable=False),
    sa.Column('linked_object_type', sa.String(length=32), nullable=False),
    sa.Column('linked_object_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_item_id'], ['regulatory_intelligence_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_object_links_intelligence_item_id'), 'intelligence_object_links', ['intelligence_item_id'], unique=False)
    sa.Enum('PLATFORM', 'CUSTOMER', name='organization_type').create(op.get_bind(), checkfirst=True)
    op.add_column(
        'organizations',
        sa.Column(
            'organization_type',
            sa.Enum('PLATFORM', 'CUSTOMER', name='organization_type'),
            nullable=False,
            server_default='CUSTOMER',  # every existing org (Layer 1/2 seed data) becomes CUSTOMER
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'organization_type')
    sa.Enum(name='organization_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_intelligence_object_links_intelligence_item_id'), table_name='intelligence_object_links')
    op.drop_table('intelligence_object_links')
    op.drop_table('intelligence_item_tags')
    op.drop_index(op.f('ix_intelligence_distributions_organization_id'), table_name='intelligence_distributions')
    op.drop_index(op.f('ix_intelligence_distributions_intelligence_item_id'), table_name='intelligence_distributions')
    op.drop_table('intelligence_distributions')
    op.drop_index(op.f('ix_regulatory_intelligence_items_status'), table_name='regulatory_intelligence_items')
    op.drop_index(op.f('ix_regulatory_intelligence_items_scope'), table_name='regulatory_intelligence_items')
    op.drop_index(op.f('ix_regulatory_intelligence_items_organization_id'), table_name='regulatory_intelligence_items')
    op.drop_index(op.f('ix_regulatory_intelligence_items_intelligence_type'), table_name='regulatory_intelligence_items')
    op.drop_table('regulatory_intelligence_items')
    op.drop_table('intelligence_sources')
    op.drop_table('intelligence_tags')
    # ### end Alembic commands ###
