"""0002 layer 2 dossier and ctd foundation

Revision ID: df4721c77cfb
Revises: 310c73f6d7fc
Create Date: 2026-09-26 16:26:41.069354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4721c77cfb'
down_revision = '310c73f6d7fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Manually added (Alembic's autogenerate does not detect new labels
    # on an existing Postgres enum type): extend permission_domain for
    # Layer 2's five new domains. Each ADD VALUE runs in its own
    # statement outside of being consumed in the same transaction, which
    # is what Postgres 12+ requires.
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'PRODUCT'")
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'AUTHORITY'")
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'APPLICATION'")
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'DOSSIER'")
    op.execute("ALTER TYPE permission_domain ADD VALUE IF NOT EXISTS 'ACTIVITY'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_authorities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('authority_type', sa.Enum('NATIONAL', 'REGIONAL', 'OTHER', name='authority_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='authority_status'), nullable=False),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('configuration_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('ctd_modules',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ctd_sections',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('standard_version_id', sa.UUID(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('applicability', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['ctd_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['ctd_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'section_code', 'authority_id', name='uq_ctd_section_identity')
    )
    op.create_index(op.f('ix_ctd_sections_module_id'), 'ctd_sections', ['module_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_family', sa.String(length=255), nullable=True),
    sa.Column('active_ingredient', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=128), nullable=True),
    sa.Column('strength', sa.String(length=128), nullable=True),
    sa.Column('route_of_administration', sa.String(length=128), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('development_status', sa.Enum('PRECLINICAL', 'CLINICAL_DEVELOPMENT', 'MARKETED', 'DISCONTINUED', name='development_status'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='product_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_business_unit_id'), 'products', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('regulatory_applications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('country_region', sa.String(length=64), nullable=False),
    sa.Column('application_type', sa.Enum('MARKETING_AUTHORIZATION', 'VARIATION', 'SUPPLEMENT', 'RENEWAL', 'CLINICAL_TRIAL', 'OTHER', name='regulatory_application_type'), nullable=False),
    sa.Column('application_number', sa.String(length=128), nullable=True),
    sa.Column('regulatory_status', sa.String(length=128), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='application_lifecycle_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_applications_authority_id'), 'regulatory_applications', ['authority_id'], unique=False)
    op.create_index(op.f('ix_regulatory_applications_organization_id'), 'regulatory_applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regulatory_applications_product_id'), 'regulatory_applications', ['product_id'], unique=False)
    op.create_table('regulatory_portfolios',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_portfolios_organization_id'), 'regulatory_portfolios', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regulatory_portfolios_product_id'), 'regulatory_portfolios', ['product_id'], unique=False)
    op.create_table('dossiers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_application_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('ctd_standard', sa.String(length=32), nullable=False),
    sa.Column('standard_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'ACTIVE', 'LOCKED', 'ARCHIVED', name='dossier_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('dossier_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regulatory_application_id'], ['regulatory_applications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_organization_id'), 'dossiers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dossiers_product_id'), 'dossiers', ['product_id'], unique=False)
    op.create_index(op.f('ix_dossiers_regulatory_application_id'), 'dossiers', ['regulatory_application_id'], unique=False)
    op.create_index(op.f('ix_dossiers_status'), 'dossiers', ['status'], unique=False)
    op.create_table('regulatory_activities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_application_id', sa.UUID(), nullable=True),
    sa.Column('dossier_id', sa.UUID(), nullable=True),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('INITIAL_SUBMISSION', 'VARIATION', 'RENEWAL', 'SUPPLEMENT', 'RESPONSE', 'DEFICIENCY', 'POST_APPROVAL_CHANGE', 'OTHER', name='regulatory_activity_type'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='regulatory_activity_status'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('activity_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regulatory_application_id'], ['regulatory_applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_activities_dossier_id'), 'regulatory_activities', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_regulatory_activities_organization_id'), 'regulatory_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regulatory_activities_product_id'), 'regulatory_activities', ['product_id'], unique=False)
    op.create_index(op.f('ix_regulatory_activities_regulatory_application_id'), 'regulatory_activities', ['regulatory_application_id'], unique=False)
    op.create_index(op.f('ix_regulatory_activities_status'), 'regulatory_activities', ['status'], unique=False)
    op.create_table('document_ctd_placements',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('ctd_section_id', sa.UUID(), nullable=False),
    sa.Column('regulatory_activity_id', sa.UUID(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('placed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ctd_section_id'], ['ctd_sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regulatory_activity_id'], ['regulatory_activities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'dossier_id', 'ctd_section_id', name='uq_document_placement')
    )
    op.create_index(op.f('ix_document_ctd_placements_ctd_section_id'), 'document_ctd_placements', ['ctd_section_id'], unique=False)
    op.create_index(op.f('ix_document_ctd_placements_document_id'), 'document_ctd_placements', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_ctd_placements_dossier_id'), 'document_ctd_placements', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_document_ctd_placements_organization_id'), 'document_ctd_placements', ['organization_id'], unique=False)
    op.create_table('regulatory_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('DOSSIER_CREATED', 'DOSSIER_STATUS_CHANGED', 'DOCUMENT_ADDED', 'DOCUMENT_REVISED', 'REVIEW_STARTED', 'REVIEW_COMPLETED', 'ACTIVITY_CREATED', 'ACTIVITY_STATUS_CHANGED', 'SUBMISSION_CREATED', 'SUBMISSION_LOCKED', 'QUERY_RECEIVED', 'RESPONSE_SUBMITTED', name='regulatory_event_type'), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=True),
    sa.Column('regulatory_activity_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['regulatory_activity_id'], ['regulatory_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_events_dossier_id'), 'regulatory_events', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_regulatory_events_organization_id'), 'regulatory_events', ['organization_id'], unique=False)
    op.add_column('documents', sa.Column('document_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_type')
    op.drop_index(op.f('ix_regulatory_events_organization_id'), table_name='regulatory_events')
    op.drop_index(op.f('ix_regulatory_events_dossier_id'), table_name='regulatory_events')
    op.drop_table('regulatory_events')
    op.drop_index(op.f('ix_document_ctd_placements_organization_id'), table_name='document_ctd_placements')
    op.drop_index(op.f('ix_document_ctd_placements_dossier_id'), table_name='document_ctd_placements')
    op.drop_index(op.f('ix_document_ctd_placements_document_id'), table_name='document_ctd_placements')
    op.drop_index(op.f('ix_document_ctd_placements_ctd_section_id'), table_name='document_ctd_placements')
    op.drop_table('document_ctd_placements')
    op.drop_index(op.f('ix_regulatory_activities_status'), table_name='regulatory_activities')
    op.drop_index(op.f('ix_regulatory_activities_regulatory_application_id'), table_name='regulatory_activities')
    op.drop_index(op.f('ix_regulatory_activities_product_id'), table_name='regulatory_activities')
    op.drop_index(op.f('ix_regulatory_activities_organization_id'), table_name='regulatory_activities')
    op.drop_index(op.f('ix_regulatory_activities_dossier_id'), table_name='regulatory_activities')
    op.drop_table('regulatory_activities')
    op.drop_index(op.f('ix_dossiers_status'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_regulatory_application_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_product_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_organization_id'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_regulatory_portfolios_product_id'), table_name='regulatory_portfolios')
    op.drop_index(op.f('ix_regulatory_portfolios_organization_id'), table_name='regulatory_portfolios')
    op.drop_table('regulatory_portfolios')
    op.drop_index(op.f('ix_regulatory_applications_product_id'), table_name='regulatory_applications')
    op.drop_index(op.f('ix_regulatory_applications_organization_id'), table_name='regulatory_applications')
    op.drop_index(op.f('ix_regulatory_applications_authority_id'), table_name='regulatory_applications')
    op.drop_table('regulatory_applications')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_unit_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ctd_sections_module_id'), table_name='ctd_sections')
    op.drop_table('ctd_sections')
    op.drop_table('ctd_modules')
    op.drop_table('regulatory_authorities')
    # ### end Alembic commands ###
