"""0004 intelligence event types and fk

Revision ID: f11f36a94de1
Revises: da97e73093ce
Create Date: 2026-09-27 07:43:53.818601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11f36a94de1'
down_revision = 'da97e73093ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TYPE regulatory_event_type ADD VALUE IF NOT EXISTS 'INTELLIGENCE_PUBLISHED'")
    op.execute("ALTER TYPE regulatory_event_type ADD VALUE IF NOT EXISTS 'INTELLIGENCE_STATUS_CHANGED'")
    op.execute("ALTER TYPE regulatory_event_type ADD VALUE IF NOT EXISTS 'INTELLIGENCE_DISTRIBUTED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_events', sa.Column('intelligence_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_regulatory_events_intelligence_item_id'), 'regulatory_events', ['intelligence_item_id'], unique=False)
    op.create_foreign_key(None, 'regulatory_events', 'regulatory_intelligence_items', ['intelligence_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regulatory_events', type_='foreignkey')
    op.drop_index(op.f('ix_regulatory_events_intelligence_item_id'), table_name='regulatory_events')
    op.drop_column('regulatory_events', 'intelligence_item_id')
    # ### end Alembic commands ###
